name: Build and Push Docker Image

on: 
  pull_request:

  push:
    branches:
      - main

  schedule:
    - cron: '0 9 * * WED' # 9:00am every Wednesday

permissions:
  contents: read
  packages: write

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:  
  docker:
    name: "Build and Push Docker Image"
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - name: ubuntu-2004-ansible
          - name: ubuntu-2204-ansible
          - name: ubuntu-2404-ansible

    steps:     
      # https://github.com/actions/checkout
      - name: Checkout repo
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          fetch-depth: 0

      - name: Check if image has been modified
        id: changes
        uses: ./.github/actions/get-changes
          
      - name: Building docker image
        if: ${{ steps.changes.outputs.has_changes }}
        uses: ./.github/actions/docker-build
        with:
          docker-username: ${{ github.actor }}
          docker-password: ${{ secrets.GITHUB_TOKEN }}
          image: ${{ matrix.name }}
          context: "./images/${{ matrix.name }}"