name: Build and Push Docker Image

on: 
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: '0 9 * * WED' # 9:00am every Wednesday

permissions:
  contents: read
  packages: write

jobs:  

  push:
    name: "Build and Push Docker Image"
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - name: ubuntu-2004-ansible
          - name: ubuntu-2204-ansible
          - name: ubuntu-2404-ansible

    steps:     
      # https://github.com/actions/checkout
      - name: Checkout repo
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          fetch-depth: 0

      - name: Check if image has been modified
        id: changes
        run: |        
          files_changed=$(git diff --name-only --diff-filter=d HEAD^..HEAD)

          # Check if changes is empty
          if [ -z "$files_changed" ]; then
              echo "No changes detected."
              echo "has_changes=false" >> $GITHUB_OUTPUT
              exit 0
          fi

          dirs_changed=$(echo "$files_changed" | grep "^images/" | cut -d'/' -f2 | sort | uniq | jq -R -s -c 'split("\n")[:-1]')

          # Check if no changes
          if [[ $(echo "$dirs_changed" | jq 'length') -eq 0 ]]; then
              echo "No changes in ./images detected."
              echo "has_changes=false" >> $GITHUB_OUTPUT
          exit 0
          fi

          echo "has_changes=true"  >> $GITHUB_OUTPUT
          
      - name: Building docker image
        if: ${{ steps.changes.outputs.has_changes }}
        uses: ./.github/actions/docker-build
        with:
          image: ${{ matrix.name }}
          file: "./images/${{ matrix.name }}/Dockerfile"