name: Dependabot auto-merge

on: 
  # Allow action-workflow to use on pull request changes
  pull_request:

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:

      # https://github.com/dependabot/fetch-metadata
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@08eff52bf64351f401fb50d4972fa95b9f2c2d1b # v2.4.0
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Enable auto-approve and merge for Dependabot PRs
        if: steps.metadata.outputs.update-type == 'version-update:semver-patch' || 
            steps.metadata.outputs.update-type == 'version-update:semver-minor'
        run: |
          # auto approve PR
          gh pr review --approve "$PR_URL"

          # merge approved PR
          gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}